name: Supabase CLI Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase init
      - run: supabase db start
      - run: supabase link --project-ref ${{ secrets.PROJECT_ID }}
      - run: supabase db push
